/* Generated by theme-set — do not edit manually */
@define-color background-color {{ background }};
@define-color border-color      {{ border_color }};
@define-color label             {{ foreground }};
@define-color image             {{ foreground }};
@define-color progress          {{ accent }};
