/* Generated by theme-set — do not edit manually */
@define-color accent      {{ accent }};
@define-color foreground  {{ foreground }};
@define-color background  {{ background }};
@define-color bg-alt      {{ bg_alt }};
@define-color border      {{ border_color }};
@define-color comment     {{ comment }};

window {
  background: alpha(@background, 0.95);
  border: 1px solid @border;
  border-radius: 12px;
}

#box {
  padding: 12px;
}

#input {
  background: @bg-alt;
  color: @foreground;
  border: 1px solid @border;
  border-radius: 8px;
  padding: 8px 12px;
  margin-bottom: 8px;
  font-family: "JetBrainsMono Nerd Font";
  font-size: 14px;
}

#input:focus {
  border-color: @accent;
}

#list {
  background: transparent;
}

row {
  border-radius: 6px;
  padding: 4px 8px;
  color: @foreground;
  font-family: "JetBrainsMono Nerd Font";
  font-size: 13px;
}

row:selected,
row:hover {
  background: @bg-alt;
  color: @accent;
}
