/* Generated by theme-set — do not edit manually */
@define-color background  {{ background }};
@define-color bg-dark     {{ bg_dark }};
@define-color bg-alt      {{ bg_alt }};
@define-color border      {{ border_color }};
@define-color foreground  {{ foreground }};
@define-color fg-bright   {{ cursor }};
@define-color accent      {{ accent }};
@define-color red         {{ color1 }};
@define-color green       {{ color2 }};
@define-color yellow      {{ color3 }};
@define-color blue        {{ accent }};
@define-color purple      {{ color13 }};
@define-color cyan        {{ cyan }};
@define-color comment     {{ comment }};
