/* Generated by theme-set — do not edit manually */
window {
  background-color: {{ background }};
  border: 1px solid {{ border_color }};
  border-radius: 12px;
  font-family: "JetBrainsMono Nerd Font";
}

#input {
  background-color: {{ bg_alt }};
  color: {{ foreground }};
  border: 1px solid {{ border_color }};
  border-radius: 8px;
  padding: 8px 12px;
  margin: 8px;
}

#input:focus {
  border-color: {{ accent }};
  outline: none;
}

#scroll {
  margin: 0 8px 8px 8px;
}

#inner-box {
  background-color: transparent;
}

#outer-box {
  padding: 4px;
}

.entry {
  padding: 6px 10px;
  border-radius: 6px;
  color: {{ foreground }};
}

.entry:selected {
  background-color: {{ bg_alt }};
  color: {{ accent }};
}

.entry image {
  margin-right: 6px;
}
